/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package manvi_workspace;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.hibernate.Transaction;

public class App {

    public static void main(String[] args) {
    
       
       Student s1 = new Student();       
       s1.setUsn("17cs71");
       s1.setName("Abhilasha");
       s1.setAdharno("asdf");
       
       Student s2 = new Student();       
       s2.setUsn("17cs72");
       s2.setName("Aditya");
       s2.setAdharno("asdfg");
       
       Course c1 = new Course();
       c1.setCid(101);
       c1.setName("dbms");
       
       Course c2 = new Course();
       c2.setCid(102);
       c2.setName("os");
     
       //c1.getStudent().add(s1);
       //c1.getStudent().add(s2);
       
       s1.getCourse().add(c1); 
       s1.getCourse().add(c2);
       
       s2.getCourse().add(c1); 
       s2.getCourse().add(c2);
       
       Department d1 = new Department();
       d1.setDepid(1);;
       d1.setHod("Prof. Nirmala");
       d1.getStud().add(s1);
       
       Laptops l1 = new Laptops();
       l1.setLid("L01");
       l1.setName("HP");
       l1.setSt(s1);
       
       
       
       Configuration cfg = new Configuration();
       cfg.configure();
    	
       SessionFactory sf = cfg.buildSessionFactory();
    	
       Session session = sf.openSession();
       
       Transaction tx = session.beginTransaction(); //to persist data into db    
       
       session.save(s1);
       session.save(c1);
       session.save(s2);
       session.save(c2);
       session.save(d1);
       session.save(l1);
       
       
       tx.commit();
       session.close();

       
       
       
       
       
    }
}
